import 'package:flutter/material.dart';
const PrimaryGreen = Color(0xff0c22b2);
const PrimaryDarkGreen = Color(0xff157963);
const Red =  Colors.red;
const purple= Colors.deepPurple;
const blue=Colors.blue;
const grey=Colors.grey;
const black=Colors.black87;
const white=Colors.white;
const green=Colors.greenAccent;
const transparent=Colors.transparent;
// const Primaryblue=Color(0xFF03A9F4);
const greenAccent=Color(0xFF66BB6A);
// const blueAccent=Color(0xFF42A5F5);